### ISSUE TITLE
statsdisplay gone 

### ISSUE THREAD

**Issue by vampstar333** [Wet-Boys/LookingGlass#147]
the statsdisplay works perfectly fine until i reach stage 2, then it refuses to work for the rest of the run. disabling it in settings and re enabling mid run does nothing

**Comment by ToastedOven** [comment]
assuming it's consistent, are you able to provide a log from a run where it happened so I can see the error?

**Comment by anartoast** [comment]
hi i believe i got something similar, if not the same.
[message(7).txt](https://github.com/user-attachments/files/18433068/message.7.txt)
the error is
```
6234 [02:54:59.8786661] [Error  : Unity Log] NullReferenceException
Stack trace:
UnityEngine.GameObject.GetComponentsInChildren[T] (System.Boolean includeInactive) (at <a20b3695b7ce4017b7981f9d06962bd1>:IL_0001)
UnityEngine.GameObject.GetComponentsInChildren[T] () (at <a20b3695b7ce4017b7981f9d06962bd1>:IL_0001)
LookingGlass.StatsDisplay.StatsDisplayClass.CalculateStuff (System.String statsText) (at /home/runner/work/LookingGlass/LookingGlass/LookingGlass/StatsDisplay/StatsDisplayClass.cs:208)
LookingGlass.StatsDisplay.StatsDisplayClass.Update () (at /home/runner/work/LookingGlass/LookingGlass/LookingGlass/StatsDisplay/StatsDisplayClass.cs:453)
LookingGlass.BasePlugin.Update () (at /home/runner/work/LookingGlass/LookingGlass/LookingGlass/BasePlugin.cs:109
```)

**Comment by ToastedOven** [comment]
Pushing up a potential fix. At the very least should fix the error anartoast sent. Let me know if it keeps happening post 1.10.2

**Comment by anartoast** [comment]
still happening :(
here's a video of it (i forgor to mention its not my log, its from a person in tech support):
https://discord.com/channels/562704639141740588/562711077453037589/1329559390176673923
log: 
[LogOutput (8).log](https://github.com/user-attachments/files/18445495/LogOutput.8.log)

**Comment by ToastedOven** [comment]
could you do me a favor and send me a profile code? I can't seem to replicate the issue on my end and there isn't even a related error in that log. I'm thinking it might be a conflict of sorts

**Comment by BaeHex** [comment]
Hey hey! I am the one who has found that bug(thank you so much for replying for me, Anartoast :D). I'll give you a brief rundown on what is happening on it so maybe there's a future solution: 

Before a stage transition happens, the stats display screen decides to poof out of existence. Every time it tries to change a variable for you to know(like total damage, speed, etc.), an error log comes up. However, the stats screen does not show up. Even if you were to hide and unhide, or use the secondary stats display, nothing happens. Looking at your scoreboard and back does not do anything, either. That was a previous, quirky bug, which does not happen anymore.

When you first drop in on-stage, the stats screen is completely fine. Utilizing the ProperSave mod as well, you can drop in on the stage you last played and it'll be fine as well. However, as soon as you change stages, LookingGlass' Stats display goes away, until you back out to main lobby and go back on that stage.

That is pretty much it. It's a pretty harmless bug, one of which also happens at random. I tried replicating it again to hand you my profile code, but the bug stopped magically. It's like that one cousin that likes to be the devil'angel and play pranks on you every once in a while. The latest log file on here has the error, any other log file will have the same error; whenever it happens again. 

So yea! So far it's working as intended. I'll grab another log file when it happens again. For now, bug is sat down.

**Comment by vampstar333** [comment]
> could you do me a favor and send me a profile code? I can't seem to replicate the issue on my end and there isn't even a related error in that log. I'm thinking it might be a conflict of sorts

01949841-6a4c-d7d6-449e-0f7da9d7fdd6

**Comment by lordhaseo** [comment]
this is also happening to me so im going to put my code to so maybe you can see if we have something in common that may be doing it 
01949f6f-75e8-dccf-14dc-462ec2e72adf

**Comment by vampstar333** [comment]
> this is also happening to me with going to any stage after 1 so im going to put my code to so maybe you can see if we have something in common that may be doing it 01949f6f-75e8-dccf-14dc-462ec2e72adf

did you manage to find out what caused it ? i still have the same problem

**Comment by Fasilina** [comment]
I have the same problem. When I reinstalled the mod, even the statistics disappeared. Nothing works.

**Comment by vampstar333** [comment]
still happens :(

**Comment by dannyduartemgs** [comment]
I have the same error. Adding my comment here to see if this was fixed.
